import { notFound } from 'next/navigation'
import { hasLocale, getDictionary, type Locale } from '@/lib/dictionaries'
import SpeakersClient from './SpeakersClient'
import Newsletter from '@/components/Newsletter'

const speakers = [
  {
    id: '1',
    name: 'Dr. Maher Samuel',
    name_ar: 'د. ماهر صموئيل',
    title: 'Founder of Credologos',
    title_ar: 'مؤسس Credologos',
    bio: 'Visionary founder of Credologos, bridging Christian faith with contemporary philosophical and theological discourse. Specializes in apologetics, philosophy, and psychology to present the Gospel in intellectually rigorous ways.',
    bio_ar: 'المؤسس والرؤيوي لـ Credologos، يجمع بين الإيمان المسيحي والخطاب الفلسفي واللاهوتي المعاصر. متخصص في الدفاعيات والفلسفة وعلم النفس.',
    expertise: ['Psychology', 'Philosophy', 'Theology', 'Apologetics'],
    expertise_ar: ['علم النفس', 'الفلسفة', 'اللاهوت', 'الدفاعيات'],
    topics: ['Faith & Reason', 'Christian Worldview', 'Spiritual Direction', 'Life Purpose'],
    topics_ar: ['الإيمان والعقل', 'الرؤية المسيحية', 'التوجيه الروحي', 'الهدف من الحياة'],
    image: '👨‍🎓',
    featured: true,
    credentials: "Psychologist | Master's in Philosophy and Religion - Trinity University",
    credentials_ar: 'طبيب نفسي | ماجستير الفلسفة والدين - جامعة ترينيتي',
    color: '#546AB2',
  },
  {
    id: '2',
    name: 'Wassim Sabry',
    name_ar: 'وسيم صبري',
    title: 'Philosopher & Theologian',
    title_ar: 'فيلسوف ولاهوتي',
    bio: 'Teacher and thinker exploring the intersections of philosophy, faith, and reason. Passionate about equipping believers to think deeply about their faith and engage meaningfully with contemporary philosophical questions.',
    bio_ar: 'معلم ومفكر يستكشف التقاطعات بين الفلسفة والإيمان والعقل. متحمس لتجهيز المؤمنين للتفكير العميق في إيمانهم.',
    expertise: ['Philosophy', 'Christian Theology', 'Epistemology', 'Logic'],
    expertise_ar: ['الفلسفة', 'اللاهوت المسيحي', 'نظرية المعرفة', 'المنطق'],
    topics: ['Truth Seeking', 'Faith & Philosophy', 'Apologetics', 'Critical Thinking'],
    topics_ar: ['البحث عن الحقيقة', 'الإيمان والفلسفة', 'الدفاعيات', 'التفكير النقدي'],
    image: '🧠',
    featured: true,
    credentials: "Master's in Philosophy - American University in Cairo (AUC)",
    credentials_ar: 'ماجستير الفلسفة - الجامعة الأمريكية بالقاهرة',
    color: '#1a7a8a',
  },
  {
    id: '3',
    name: 'Youssef Yaqoub',
    name_ar: 'يوسف يعقوب',
    title: 'Philosophy of Science & Religion',
    title_ar: 'فلسفة العلم والدين',
    bio: 'Specialized in the dialogue between science and faith, helping audiences understand how scientific discoveries complement rather than contradict Christian belief.',
    bio_ar: 'متخصص في الحوار بين العلم والإيمان، يساعد الجماهير على فهم كيف تكمل الاكتشافات العلمية الإيمان المسيحي.',
    expertise: ['Science & Faith', 'Philosophy of Science', 'Communication', 'Cultural Engagement'],
    expertise_ar: ['العلم والإيمان', 'فلسفة العلم', 'التواصل', 'الانخراط الثقافي'],
    topics: ['God & Science', 'Evolution & Faith', 'Scientific Worldview', 'Truth Integration'],
    topics_ar: ['الله والعلم', 'التطور والإيمان', 'الرؤية العلمية', 'تكامل الحقيقة'],
    image: '🔬',
    featured: true,
    credentials: "Master's in Philosophy of Science and Religion - University of Edinburgh",
    credentials_ar: 'ماجستير فلسفة العلم والدين - جامعة إدنبره',
    color: '#2d7a52',
  },
  {
    id: '4',
    name: 'Hesham Hashmat',
    name_ar: 'حسام حشمت',
    title: 'Theologian & Biblical Scholar',
    title_ar: 'لاهوتي وباحث كتابي',
    bio: 'Dedicated to helping believers understand the theological foundations of Christian faith. Focuses on scriptural truth, church history, and systematic theology.',
    bio_ar: 'مكرس لمساعدة المؤمنين على فهم الأسس اللاهوتية للإيمان المسيحي. يركز على الحقيقة الكتابية وتاريخ الكنيسة واللاهوت النظامي.',
    expertise: ['Theology', 'Biblical Studies', 'Systematic Theology', 'Church History'],
    expertise_ar: ['اللاهوت', 'الدراسات الكتابية', 'اللاهوت النظامي', 'تاريخ الكنيسة'],
    topics: ['Christian Foundations', 'Scriptural Truth', 'Redemption Story', 'Doctrine'],
    topics_ar: ['الأسس المسيحية', 'الحقيقة الكتابية', 'قصة الفداء', 'العقيدة'],
    image: '📖',
    featured: false,
    credentials: "Master's in Theology - Princeton Theological Seminary",
    credentials_ar: 'ماجستير اللاهوت - كلية اللاهوت ببرنستون',
    color: '#7a2d6e',
  },
  {
    id: '5',
    name: 'Andrew Ashraf',
    name_ar: 'أندرو أشرف',
    title: 'Literature & Communication',
    title_ar: 'الأدب والتواصل',
    bio: 'Brings literary perspective to theological discussions, finding theological truth in narrative and story. Expert at communicating complex faith concepts through compelling storytelling.',
    bio_ar: 'يجلب منظور أدبي للنقاشات اللاهوتية، ويجد الحقيقة اللاهوتية في السرد والقصة.',
    expertise: ['Literature', 'Communication', 'Narrative Theology', 'Cultural Analysis'],
    expertise_ar: ['الأدب', 'التواصل', 'اللاهوت السردي', 'التحليل الثقافي'],
    topics: ['Gospel Narratives', 'Cultural Engagement', 'Apologetics', 'Storytelling'],
    topics_ar: ['سرديات الإنجيل', 'الانخراط الثقافي', 'الدفاعيات', 'رواية القصص'],
    image: '📚',
    featured: false,
    credentials: "Master's in Modern and Contemporary Literature - University of Nottingham",
    credentials_ar: 'ماجستير الأدب الحديث والمعاصر - جامعة نوتينجهام',
    color: '#a0650e',
  },
  {
    id: '6',
    name: 'Amir Karam',
    name_ar: 'أمير كرم',
    title: 'Dentist & Theologian',
    title_ar: 'طبيب أسنان ولاهوتي',
    bio: 'Healthcare professional dedicated to exploring the integration of faith and science. Brings a unique perspective on medical ethics and spiritual wellness in modern healthcare.',
    bio_ar: 'متخصص في الرعاية الصحية مكرس لاستكشاف تكامل الإيمان والعلم. يجلب منظور فريد حول كيف يمكن للمؤمنين التعامل مع الأخلاقيات الطبية.',
    expertise: ['Healthcare & Faith', 'Medical Ethics', 'Theology', 'Spiritual Wellness'],
    expertise_ar: ['الرعاية الصحية والإيمان', 'الأخلاقيات الطبية', 'اللاهوت', 'الصحة الروحية'],
    topics: ['Faith in Medicine', 'Christian Ethics', 'Spiritual Health', 'Vocational Calling'],
    topics_ar: ['الإيمان والطب', 'الأخلاقيات المسيحية', 'الصحة الروحية', 'الدعوة الوظيفية'],
    image: '⚕️',
    featured: false,
    credentials: 'Dentist | Extensive Theological Studies',
    credentials_ar: 'طبيب أسنان | دراسات لاهوتية شاملة',
    color: '#2e2e8a',
  },
  {
    id: '7',
    name: 'Bassel Yaqoub',
    name_ar: 'باسل يعقوب',
    title: 'Dentist & Faith Leader',
    title_ar: 'طبيب أسنان وقائد روحي',
    bio: 'Combines professional healthcare practice with deep spiritual understanding. Passionate about demonstrating how Christian faith operates within professional environments.',
    bio_ar: 'يجمع بين ممارسة الرعاية الصحية المهنية والفهم الروحي العميق. متحمس لإظهار كيف يعمل الإيمان المسيحي في البيئات المهنية.',
    expertise: ['Professional Faith', 'Community Service', 'Christian Leadership', 'Healthcare'],
    expertise_ar: ['الإيمان المهني', 'خدمة المجتمع', 'القيادة المسيحية', 'الرعاية الصحية'],
    topics: ['Work & Calling', 'Servant Leadership', 'Community Impact', 'Faith in Practice'],
    topics_ar: ['العمل والدعوة', 'قيادة الخدمة', 'تأثير المجتمع', 'الإيمان في الممارسة'],
    image: '🦷',
    featured: false,
    credentials: 'Dentist | Biblical Leadership & Theology Student',
    credentials_ar: 'طبيب أسنان | دارس للقيادة الكتابية واللاهوت',
    color: '#546AB2',
  },
  {
    id: '8',
    name: 'Rafik Maher Samuel',
    name_ar: 'رفيق ماهر صموئيل',
    title: 'Political Science & Christianity',
    title_ar: 'العلوم السياسية والمسيحية',
    bio: 'Explores the intersection of Christian faith and political science, examining how biblical principles apply to contemporary political and social structures.',
    bio_ar: 'يستكشف تقاطع الإيمان المسيحي والعلوم السياسية، ويبحث في كيفية تطبيق المبادئ الكتابية على الهياكل السياسية والاجتماعية المعاصرة.',
    expertise: ['Political Science', 'Christian Ethics', 'Governance', 'Social Theory'],
    expertise_ar: ['العلوم السياسية', 'الأخلاقيات المسيحية', 'الحكم', 'النظرية الاجتماعية'],
    topics: ['Faith & Politics', 'Christian Citizenship', 'Social Justice', 'Kingdom Values'],
    topics_ar: ['الإيمان والسياسة', 'المواطنة المسيحية', 'العدالة الاجتماعية', 'قيم الملكوت'],
    image: '🏛️',
    featured: false,
    credentials: 'Political Science Graduate | Theological Studies',
    credentials_ar: 'خريج علوم سياسية | دراسات لاهوتية',
    color: '#1a7a8a',
  },
  {
    id: '9',
    name: 'Sherif Joseph',
    name_ar: 'شريف جوزيف',
    title: 'Economics & Spiritual Formation',
    title_ar: 'الاقتصاد والتشكيل الروحي',
    bio: 'Bridges economics and theology, addressing how Christian principles guide financial stewardship and economic justice.',
    bio_ar: 'يربط بين الاقتصاد واللاهوت، ويعالج كيفية أن تنظم المبادئ المسيحية الإدارة المالية والعدالة الاقتصادية.',
    expertise: ['Economics', 'Financial Stewardship', 'Christian Ethics', 'Economic Justice'],
    expertise_ar: ['الاقتصاد', 'الإدارة المالية', 'الأخلاقيات المسيحية', 'العدالة الاقتصادية'],
    topics: ['Faith & Finances', 'Economic Justice', 'Generosity', 'Kingdom Economics'],
    topics_ar: ['الإيمان والمالية', 'العدالة الاقتصادية', 'الكرم', 'اقتصاد الملكوت'],
    image: '💼',
    featured: false,
    credentials: 'Economics Graduate | Christian Leadership Development',
    credentials_ar: 'خريج اقتصاد | برنامج تطوير القيادة المسيحية',
    color: '#2d7a52',
  },
]

export type Speaker = typeof speakers[0]

export default async function SpeakersPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params
  if (!hasLocale(lang)) notFound()
  const dict = await getDictionary(lang as Locale)

  return <SpeakersClient lang={lang} dict={dict} speakers={speakers} />
}